using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PaperBag
{
    public static class KeyBindings
    {
        public static List<string> Binds = new List<string>
        {
            "KP_ENTER",
            "KP_MINUS",
            "KP_PLUS",
            "KP_DEL",
            "KP_INS",
            "KP_END",
            "KP_DOWNARROW",
            "KP_PGDN",
            "KP_LEFTARROW",
            "KP_5",
            "KP_RIGHTARROW",
            "KP_HOME",
            "KP_UPARROW",
            "KP_PGUP",
            "KP_SLASH",
            "KP_MULTIPLY",
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G",
            "H",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "P",
            "Q",
            "R",
            "S",
            "T",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "0",
            "F1",
            "F2",
            "F3",
            "F4",
            "F5",
            "F6",
            "F7",
            "F8",
            "F9",
            "F10",
            "F11",
            "F12",
        };
    }
}